### ISSUE TITLE
System.FormatException: Guid should contain 32 digits with 4 dashes

### ISSUE THREAD

**Issue by makuser** [jellyfin/jellyfin-plugin-tvheadend#32]
**Describe the issue you are experiencing**
Stream not starting with error in log
`System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)`

**Describe the behavior you expected**
Stream starts

**Steps to reproduce the issue**
I was not able to determine this

**What version of Jellyfin are you running?**
10.6.4 and 10.7.0

**What version of Tvheadend are you running?**
4.2.8-dmo1

**What version of the plugin has the issue?**
7.0.0.0

**jellyfin.log**
```log
[18:24:36] [INF] GetPostedPlaybackInfo profile: {"Name": "Jellyfin MPV Shim", "Id": null, "Identification": null, "FriendlyName": null, "Manufacturer": null, "ManufacturerUrl": null, "ModelName": null, "ModelDescription": null, "ModelNumber": null, "ModelUrl": null, "SerialNumber": null, "EnableAlbumArtInDidl": false, "EnableSingleAlbumArtLimit": false, "EnableSingleSubtitleLimit": false, "SupportedMediaTypes": "Audio,Photo,Video", "UserId": null, "AlbumArtPn": null, "MaxAlbumArtWidth": 0, "MaxAlbumArtHeight": 0, "MaxIconWidth": null, "MaxIconHeight": null, "MaxStreamingBitrate": 10000000, "MaxStaticBitrate": 8000000, "MusicStreamingTranscodingBitrate": 1280000, "MaxStaticMusicBitrate": null, "SonyAggregationFlags": null, "ProtocolInfo": null, "TimelineOffsetSeconds": 5, "RequiresPlainVideoItems": false, "RequiresPlainFolders": false, "EnableMSMediaReceiverRegistrar": false, "IgnoreTranscodeByteRangeRequests": false, "XmlRootAttributes": [], "DirectPlayProfiles": [{"Container": null, "AudioCodec": null, "VideoCodec": null, "Type": "Video", "$type": "DirectPlayProfile"}, {"Container": null, "AudioCodec": null, "VideoCodec": null, "Type": "Audio", "$type": "DirectPlayProfile"}, {"Container": null, "AudioCodec": null, "VideoCodec": null, "Type": "Photo", "$type": "DirectPlayProfile"}], "TranscodingProfiles": [{"Container": null, "Type": "Audio", "VideoCodec": null, "AudioCodec": null, "Protocol": null, "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "ts", "Type": "Video", "VideoCodec": "h264,h265,hevc,mpeg4,mpeg2video", "AudioCodec": "aac,mp3,ac3,opus,flac,vorbis", "Protocol": "hls", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": "6", "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}, {"Container": "jpeg", "Type": "Photo", "VideoCodec": null, "AudioCodec": null, "Protocol": null, "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "$type": "TranscodingProfile"}], "ContainerProfiles": [], "CodecProfiles": [], "ResponseProfiles": [], "SubtitleProfiles": [{"Format": "srt", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "srt", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ass", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ass", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "sub", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "sub", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ssa", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "ssa", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "smi", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "smi", "Method": "External", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "pgssub", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "dvdsub", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}, {"Format": "pgs", "Method": "Embed", "DidlMode": null, "Language": null, "Container": null, "$type": "SubtitleProfile"}], "$type": "DeviceProfile"}
[18:24:36] [INF] User policy for marc. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[18:24:36] [INF] Bitrate exceeds DirectPlay limit: media bitrate: 40000000, max bitrate: 8000000
[18:24:36] [INF] Bitrate exceeds DirectStream limit: media bitrate: 40000000, max bitrate: 10000000
[18:24:36] [INF] Profile: Jellyfin MPV Shim, Path: Unknown path, isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[18:24:36] [INF] RemoteClientBitrateLimit: 12000000, RemoteIp: 88.130.75.118, IsInLocalNetwork: False
[18:24:36] [INF] Bitrate exceeds DirectPlay limit: media bitrate: 40000000, max bitrate: 8000000
[18:24:36] [INF] Bitrate exceeds DirectStream limit: media bitrate: 40000000, max bitrate: 10000000
[18:24:36] [INF] Profile: Jellyfin MPV Shim, Path: Unknown path, isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[18:24:36] [INF] RemoteClientBitrateLimit: 12000000, RemoteIp: 88.130.75.118, IsInLocalNetwork: False
[18:24:36] [INF] Bitrate exceeds DirectPlay limit: media bitrate: 40000000, max bitrate: 8000000
[18:24:36] [INF] Bitrate exceeds DirectStream limit: media bitrate: 40000000, max bitrate: 10000000
[18:24:36] [INF] Profile: Jellyfin MPV Shim, Path: Unknown path, isEligibleForDirectPlay: False, isEligibleForDirectStream: False
[18:24:36] [INF] Opening channel stream from TVHclient LiveTvService, external channel Id: 1505957949
[18:24:36] [INF] Live stream opened after 0.0003ms
[18:24:36] [INF] Live tv media info probe took 0.0002106 seconds
[18:24:36] [INF] Live stream opened: {"Protocol":"Http","Id":"21","Path":"http://127.0.0.1:9981/stream/channelid/1505957949?ticket=1BCE93485BC52E3C902E21A03C1B99C1CB72EF56","Type":"Default","Container":"mpegts","IsRemote":false,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":true,"RequiresOpening":false,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_41c95b6de5174f82acbc56fe82d0a2f8_21","RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"h264","TimeBase":"1/90000","CodecTimeBase":"1/100","VideoRange":"SDR","DisplayTitle":"720p H264 SDR","NalLengthSize":"0","IsInterlaced":false,"BitRate":8000000,"BitDepth":8,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":720,"Width":1280,"AverageFrameRate":50,"RealFrameRate":50,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":40,"IsAnamorphic":false},{"Codec":"mp2","TimeBase":"1/90000","CodecTimeBase":"1/48000","DisplayTitle":"MP2 - Stereo","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":256000,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":-1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"MediaAttachments":[],"Formats":[],"Bitrate":8256000,"RequiredHttpHeaders":{},"AnalyzeDurationMs":3000}
[18:24:36] [INF] User policy for marc. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[18:24:36] [INF] Profile: Jellyfin MPV Shim, Path: http://127.0.0.1:9981/stream/channelid/1505957949?ticket=1BCE93485BC52E3C902E21A03C1B99C1CB72EF56, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[18:24:36] [INF] RemoteClientBitrateLimit: 12000000, RemoteIp: 88.130.75.118, IsInLocalNetwork: False
[18:24:36] [INF] Profile: Jellyfin MPV Shim, Path: http://127.0.0.1:9981/stream/channelid/1505957949?ticket=1BCE93485BC52E3C902E21A03C1B99C1CB72EF56, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[18:24:36] [INF] RemoteClientBitrateLimit: 12000000, RemoteIp: 88.130.75.118, IsInLocalNetwork: False
[18:24:36] [INF] Profile: Jellyfin MPV Shim, Path: http://127.0.0.1:9981/stream/channelid/1505957949?ticket=1BCE93485BC52E3C902E21A03C1B99C1CB72EF56, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[18:24:36] [ERR] Error processing request. URL GET /Videos/0172d7a894c21379a884b3345b379945/stream.
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
   at System.Guid.TryParseExactN(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.Parse(String input)
   at Jellyfin.Api.Helpers.StreamingHelpers.GetStreamingState(StreamingRequestDto streamingRequest, HttpRequest httpRequest, IAuthorizationContext authorizationContext, IMediaSourceManager mediaSourceManager, IUserManager userManager, ILibraryManager libraryManager, IServerConfigurationManager serverConfigurationManager, IMediaEncoder mediaEncoder, IFileSystem fileSystem, ISubtitleEncoder subtitleEncoder, IConfiguration configuration, IDlnaManager dlnaManager, IDeviceManager deviceManager, TranscodingJobHelper transcodingJobHelper, TranscodingJobType transcodingJobType, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.VideosController.GetVideoStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, SubtitleDeliveryMethod subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, EncodingContext context, Dictionary`2 streamOptions)
   at lambda_method996(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**tvheadend.log**
```log
Feb 20 18:26:55 MAKserver08 tvheadend[877]: mpegts: 10743.75H in Astra - tuning on STB0899 Multistandard #0 : DVB-S #0
Feb 20 18:26:55 MAKserver08 tvheadend[877]: subscription: 03E7: "epggrab" subscribing to mux "10743.75H", weight: 4, adapter: "STB0899 Multistandard #0 : DVB-S #0", network: "Astra", service: "Raw PID Subscription"
```

**Comment by crobibero** [comment]
Is this still an issue with Jellyfin 10.7.6 and TVH plugin v9?
