### ISSUE TITLE
[Live TV] "FFmpeg exited with code 1" due to "Error submitting video frame to the encoder"

### ISSUE THREAD

**Issue by LnLcFlx** [jellyfin/jellyfin-plugin-tvheadend#65]
When starting a live TV channel I get an error after a few seconds.

In the GUI it says (sorry German):
```
Wiedergabefehler

Dieser Client ist nicht mit den Medien kompatibel und der Server sendet kein kompatibles Medienformat.
```

Logs:
```
[2023-04-29 18:34:09.097 +00:00] [ERR] [56] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[2023-04-29 18:34:09.165 +00:00] [ERR] [56] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/8a008220-c3e6-926e-8f8f-e8dc78960d80/live.m3u8".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetLiveHlsStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 enableSubtitlesInManifest)
   at lambda_method1059(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

Here is the corresponding FFmpeg log.
```
/videos/8a008220-c3e6-926e-8f8f-e8dc78960d80/live.m3u8

{"Protocol":1,"Id":"860451279","Path":"http://tvheadend:9981/stream/channelid/860451279?ticket=7e07bafc2a46c14c64d275c79b5eb0a0f3dcc621","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":null,"Size":null,"Name":null,"IsRemote":false,"ETag":null,"RunTimeTicks":null,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":true,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":1500,"RequiresLooping":false,"SupportsProbing":true,"VideoType":null,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":null,"CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":null,"CodecTimeBase":null,"Title":null,"VideoRange":"SDR","VideoRangeType":"SDR","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"SDR","NalLengthSize":"0","IsInterlaced":true,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":1,"AspectRatio":null,"Index":-1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":null,"IsAnamorphic":null},{"Codec":null,"CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":null,"CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":-1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":null,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -autorotate 0 -i "http://tvheadend:9981/stream/channelid/860451279?ticket=7e07bafc2a46c14c64d275c79b5eb0a0f3dcc621" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 h264_vaapi -rc_mode VBR -b:v 493733647 -maxrate 493733647 -bufsize 987467294 -force_key_frames:0 "expr:gte(t,n_forced*3)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,yadif=0:-1:0,format=nv12,hwupload_vaapi" -flags -global_header -codec:a:0 libfdk_aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/9b1ef6775b08ec8d65092a2c642b6bb9/" -hls_segment_filename "/config/transcodes/9b1ef6775b08ec8d65092a2c642b6bb9%d.ts" -hls_playlist_type event -hls_list_size 0 -y "/config/transcodes/9b1ef6775b08ec8d65092a2c642b6bb9.m3u8"


ffmpeg version 5.1.3-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55f169551a80] decode_slice_header error
[h264 @ 0x55f169551a80] no frame!
[h264 @ 0x55f169551a80] mmco: unref short failure
[h264 @ 0x55f169551a80] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
[h264 @ 0x55f169551a80] Increasing reorder buffer to 2
[h264 @ 0x55f169551a80] Increasing reorder buffer to 3
Input #0, mpegts, from 'http://tvheadend:9981/stream/channelid/860451279?ticket=7e07bafc2a46c14c64d275c79b5eb0a0f3dcc621':
  Duration: N/A, start: 80263.595311, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : Das Erste HD
      service_provider: ARD
  Stream #0:0[0x13ed]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn
  Stream #0:1[0x13ee](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, 5.1(side), fltp, 448 kb/s
  Stream #0:2[0x13ef](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 192 kb/s (visual impaired) (descriptions)
  Stream #0:3[0x13f0](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006), 492x250
  Stream #0:4[0x13f1](deu): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
  Stream #0:5[0x13f3](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 192 kb/s (hearing impaired)
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (ac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[h264 @ 0x55f169546000] co located POCs unavailable
[h264 @ 0x55f169637800] co located POCs unavailable
[h264 @ 0x55f169bb6780] mmco: unref short failure
Output #0, hls, to '/config/transcodes/9b1ef6775b08ec8d65092a2c642b6bb9.m3u8':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: h264 (High), vaapi(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 493733 kb/s, 50 fps, 90k tbn
    Metadata:
      encoder         : Lavc59.37.100 h264_vaapi
  Stream #0:1: Audio: aac, 48000 Hz, stereo, s16, 384 kb/s
    Metadata:
      encoder         : Lavc59.37.100 libfdk_aac
frame=    1 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[h264_vaapi @ 0x55f169547bc0] Failed to end picture encode issue: 24 (internal encoding error).
[h264_vaapi @ 0x55f169547bc0] Encode failed: -5.
Error submitting video frame to the encoder
[libfdk_aac @ 0x55f169570240] 2 frames left in the queue on closing
Conversion failed!
```

However, TVheadend is working in Kodi for instance.

Already tried reconfiguring everything like [#24](https://github.com/jellyfin/jellyfin-plugin-tvheadend/issues/24#issuecomment-694811890).

**Comment by LnLcFlx** [comment]
Somehow fixed itself...
