### ISSUE TITLE
Plugin not loading channel icons

### ISSUE THREAD

**Issue by hardwareadictos** [jellyfin/jellyfin-plugin-tvheadend#90]
Hey!!

I just set up the plugin and i can watch the channels and get the epg infor on guide refresh, but i can't seem to make Channel icons to appear, i get this error on logs:

```
Jellyfin-TEST  | [13:04:09] [ERR] [28] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /Items/294916a531c0c9f30908b3422bb16212/Images/Primary.
Jellyfin-TEST  | System.InvalidOperationException: Unable to convert any images to local
Jellyfin-TEST  |    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure)
Jellyfin-TEST  |    at Jellyfin.Api.Controllers.ImageController.GetImageInternal(Guid itemId, ImageType imageType, Nullable`1 imageIndex, String tag, Nullable`1 format, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, Nullable`1 blur, String backgroundColor, String foregroundLayer, BaseItem item, ItemImageInfo imageInfo)
Jellyfin-TEST  |    at Jellyfin.Api.Controllers.ImageController.GetItemImage(Guid itemId, ImageType imageType, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, String tag, Nullable`1 format, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 blur, String backgroundColor, String foregroundLayer, Nullable`1 imageIndex)
Jellyfin-TEST  |    at lambda_method953(Closure, Object)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jellyfin-TEST  |    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
Jellyfin-TEST  |    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
Jellyfin-TEST  |    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
Jellyfin-TEST  |    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Jellyfin-TEST  |    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
Jellyfin-TEST  |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
Jellyfin-TEST  |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Jellyfin-TEST  |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Jellyfin-TEST  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jellyfin-TEST  |    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
Jellyfin-TEST  |    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
Jellyfin-TEST  |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
Jellyfin-TEST  |    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
Jellyfin-TEST  |    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

Thanks in advance!

**Comment by hardwareadictos** [comment]
Update: I see those errors also which for me are a no sense:

```
Jellyfin-TEST  | [10:54:01] [ERR] [46] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /Items/3908c3189a3b45e8f734ca4a950672d1/Images/Primary.
Jellyfin-TEST  | System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
Jellyfin-TEST  |    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
Jellyfin-TEST  |    at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
Jellyfin-TEST  |    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure)
Jellyfin-TEST  |    at Jellyfin.Api.Controllers.ImageController.GetImageInternal(Guid itemId, ImageType imageType, Nullable`1 imageIndex, String tag, Nullable`1 format, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, Nullable`1 blur, String backgroundColor, String foregroundLayer, BaseItem item, ItemImageInfo imageInfo)
````

I get a 401 error while i can watch the streams without issues. So my tvheadend user has permissions

**Comment by hardwareadictos** [comment]
Update 2: So i installed dream Player for TVHEadend on my Pixel 7 and i can sync all channel icons, even i am not suffering from the delay between aduio and video i'm suffering on jellyfin.

**Comment by mcblacky** [comment]
Hi,

After upgrading to Jellyfin 10.9.9 and tvheadend plugin 12.0.0.0 with HTS Tvheadend 4.3-2349~gb774bdd25 I lost my channel icons too. Glad that I am not alone but hope for a solution.


[2024-08-22 00:08:51.593 +02:00] [ERR] [90] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Items/b8843a1be47fc98aa6028fd34b8fb13c/Images/Primary".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure)
   at Jellyfin.Api.Controllers.ImageController.GetImageInternal(Guid itemId, ImageType imageType, Nullable`1 imageIndex, String tag, Nullable`1 format, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, Nullable`1 blur, String backgroundColor, String foregroundLayer, BaseItem item, ItemImageInfo imageInfo)
   at Jellyfin.Api.Controllers.ImageController.GetItemImage(Guid itemId, ImageType imageType, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, String tag, Nullable`1 format, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 blur, String backgroundColor, String foregroundLayer, Nullable`1 imageIndex)
   at lambda_method765(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by hardwareadictos** [comment]
> Hi,
> 
> After upgrading to Jellyfin 10.9.9 and tvheadend plugin 12.0.0.0 with HTS Tvheadend 4.3-2349~gb774bdd25 I lost my channel icons too. Glad that I am not alone but hope for a solution.
> 
> [2024-08-22 00:08:51.593 +02:00] [ERR] [90] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Items/b8843a1be47fc98aa6028fd34b8fb13c/Images/Primary". System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized). at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure) at Jellyfin.Api.Controllers.ImageController.GetImageInternal(Guid itemId, ImageType imageType, Nullable`1 imageIndex, String tag, Nullable`1 format, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, Nullable`1 blur, String backgroundColor, String foregroundLayer, BaseItem item, ItemImageInfo imageInfo) at Jellyfin.Api.Controllers.ImageController.GetItemImage(Guid itemId, ImageType imageType, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 width, Nullable`1 height, Nullable`1 quality, Nullable`1 fillWidth, Nullable`1 fillHeight, String tag, Nullable`1 format, Nullable`1 percentPlayed, Nullable`1 unplayedCount, Nullable`1 blur, String backgroundColor, String foregroundLayer, Nullable`1 imageIndex) at lambda_method765(Closure, Object) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

Hey! Seems that Jellyfin is not 100% compatible with TVHeadend authentication.

Followed this steps to get this fixed: https://emby.media/community/index.php?/topic/71181-tvheadend-and-emby/

Just create a * user without password, for me it allowed me to add TVHeadend channel and URL on Live TV settings instead the plugin.

For me overall experience is far better without the plugin, icons loads and i don't have that messy out of sync audio with image that i have with the plugin.

**Comment by mcblacky** [comment]
Many thanks for quick responding!

> just create a * user without password, for me it allowed me to add TVHeadend channel and URL on Live TV settings instead the plugin.

I did make a * user as per  https://emby.media/community/index.php?/topic/71181-tvheadend-and-emby/

But how did you add TVHeadend channel and URL on Live TV settings. In Jellyfin Live TV settings, I am only able to select HDHomerun and M3U tuner. With option Other, I am only able to do an auto detect. No way to add an URL.

I tried to connect to TVheadend with the plugin without entering username and password but is not connecting. But as I read your message you are not using the plug in. Could you please explain a bit more clear, thanks in advance.

**Comment by hardwareadictos** [comment]
> Many thanks for quick responding!
> 
> > just create a * user without password, for me it allowed me to add TVHeadend channel and URL on Live TV settings instead the plugin.
> 
> I did make a * user as per https://emby.media/community/index.php?/topic/71181-tvheadend-and-emby/
> 
> But how did you add TVHeadend channel and URL on Live TV settings. In Jellyfin Live TV settings, I am only able to select HDHomerun and M3U tuner. With option Other, I am only able to do an auto detect. No way to add an URL.
> 
> I tried to connect to TVheadend with the plugin without entering username and password but is not connecting. But as I read your message you are not using the plug in. Could you please explain a bit more clear, thanks in advance.

No problem, it's really easy, under Live TV settings add an m3u tunner:

![image](https://github.com/user-attachments/assets/f6b852cf-8327-4cc5-9b59-ce4a5a540b64)

And for EPG add something like this xmltv entry:

![image](https://github.com/user-attachments/assets/f468d42f-3452-4b23-91c6-bcc4218af0ee)

That must be documented also on Jellyfin docs, i did find this information on Emby forums. Nothing on Jellyfin Documentation.

**Comment by mcblacky** [comment]
hardwareadictos Mucho Gracias,

I had to remove the Jellyfin docker container and the library directory and started from scratch. With your settings the channel icons are back again! But it looks like Jellyfin is using more CPU than before and during watching realtime HD streams it stops now and than (asking to much from my raspberrypi5). With the tvheadend this didn't happen. But the appearance looking more colorful now. Thanks a lot for your help. The makers of tvheadend plugin need to do a bit on the authentication.

**Comment by D3rSchurk3** [comment]
Same symptom here: channel icons fail with 401, streaming/EPG work fine with the same TVH user. Findings + workaround below.

**Environment:**
- Jellyfin server: `10.11.11`
- `jellyfin-plugin-tvheadend`: `v13.0.0.0` (latest at time of testing)
- Tvheadend: `4.3-2747~ga502d063c` (recent nightly build, Cloudsmith repo)
- Tvheadend and Jellyfin on separate hosts/containers on the same LAN

## Root cause

`HTSConnectionHandler.cs`, `GetChannelImageUrl()`:

```csharp
public string GetChannelImageUrl(string channelId)
{
    ...
    if (channelIcon.StartsWith("http"))
    {
        return _channelDataHelper.GetChannelIcon4ChannelId(channelId);
    }
    else
    {
        return "http://" + _userName + ":" + _password + "@" +
               _tvhServerName + ":" + _httpPort + _webRoot + "/" + channelIcon;
    }
}
```

This embeds credentials using the `http://user:pass@host/...` userinfo syntax. `HttpClient` (used by Jellyfin core in `ProviderManager.SaveImage` → `ConvertImageToLocal`) doesn't parse userinfo-in-URL into an `Authorization` header, so the outgoing request has **no auth header at all**, regardless of the plugin settings.

Stream URLs don't have this problem because they go through `AccessTicketHandler`/`getTicket` over HTSP and end up as `{path}?ticket={ticket}` — the icon path is the only one that skips the ticket mechanism.

## Verification

`/imagecache` requires the requesting user to have at least one of `ACCESS_WEB_INTERFACE / ACCESS_STREAMING / ACCESS_ADVANCED_STREAMING / ACCESS_HTSP_STREAMING / ACCESS_HTSP_RECORDER / ACCESS_RECORDER` (see `page_imagecache` in `src/webui/webui.c`). With a TVH user matching the permissions this plugin's own docs recommend:

```
# Same TVH user, same imagecache resource:
curl --digest -u "jellyfin:PASSWORD" http://<tvh>:9981/imagecache/1050   → 200 OK
curl                                  http://<tvh>:9981/imagecache/1050   → 401 Unauthorized
```

Server side works fine once a proper Digest handshake happens; the plugin just never attempts one for this URL. TVH-side variables suggested elsewhere (anonymous `*` user, `digest_algo` MD5 vs SHA, "Plain + Digest" auth mode) don't change the outcome, since the client sends no credentials in the first place.

## Suggested fix

Route `GetChannelImageUrl()` through the same ticket mechanism already used for streams (`AccessTicketHandler`): request a `channel` ticket for the icon and return `{imagecache_path}?ticket={ticket}` instead of embedding `user:pass@` in the URL.

Separately: even once auth succeeds, Tvheadend sends no `Content-Type` header for `/imagecache/*`. Some HTTP clients default that to `application/octet-stream`, which Jellyfin's image pipeline silently discards instead of persisting. Worth setting `Content-Type: image/<format>` explicitly if the fix goes through a client that doesn't infer it from the bytes.

## Workaround

Auth-fixing reverse proxy in front of Tvheadend, running on the Tvheadend host. Passes everything through unmodified except `/imagecache/*`, which it authenticates on the plugin's behalf and re-serves with `Content-Type: image/png`. Point the plugin's HTTP/HTSP port settings at the proxy instead of Tvheadend's real ports.

Requires `aiohttp` (`python3-aiohttp` or `pip install aiohttp`). Set `TVH_USER`/`TVH_PASS`, adjust ports if needed:

```python
#!/usr/bin/env python3
"""Auth-fixing reverse proxy in front of Tvheadend for Jellyfin's TVHeadend plugin.

Jellyfin's plugin builds image URLs as http://user:pass@host/imagecache/X, but
Jellyfin's HttpClient never sends those embedded credentials, so TVH rejects
the request with 401. This proxy authenticates on the client's behalf for
/imagecache/* and passes everything else through unmodified.

- HTTP  (default 19981) -> TVH HTTP  (127.0.0.1:9981)
- HTSP  (default 19982) -> TVH HTSP  (127.0.0.1:9982), raw TCP passthrough
"""
import asyncio
import logging

import aiohttp
from aiohttp import web

TVH_HOST = "127.0.0.1"
TVH_HTTP_PORT = 9981
TVH_HTSP_PORT = 9982

PROXY_HTTP_PORT = 19981
PROXY_HTSP_PORT = 19982

TVH_USER = "jellyfin"
TVH_PASS = "CHANGE_ME"

HOP_BY_HOP = {
    "connection", "keep-alive", "proxy-authenticate", "proxy-authorization",
    "te", "trailers", "transfer-encoding", "upgrade",
    "content-encoding", "content-length", "authorization", "host",
}

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("tvh-proxy")


async def handle_http(request: web.Request) -> web.StreamResponse:
    target_url = f"http://{TVH_HOST}:{TVH_HTTP_PORT}{request.path}"

    auth = None
    if request.path.startswith("/imagecache/"):
        auth = aiohttp.BasicAuth(TVH_USER, TVH_PASS)

    fwd_headers = {k: v for k, v in request.headers.items() if k.lower() not in HOP_BY_HOP}

    session: aiohttp.ClientSession = request.app["session"]
    try:
        async with session.request(
            request.method,
            target_url,
            params=request.query,
            headers=fwd_headers,
            data=request.content if request.can_read_body else None,
            auth=auth,
            allow_redirects=False,
        ) as resp:
            resp_headers = {k: v for k, v in resp.headers.items() if k.lower() not in HOP_BY_HOP}
            if request.path.startswith("/imagecache/"):
                # TVH sends no Content-Type for imagecache; aiohttp then fills in
                # a synthetic "application/octet-stream", which Jellyfin silently
                # refuses to save as an image. Picons are PNGs, so set it explicitly.
                resp_headers["Content-Type"] = "image/png"
            proxy_resp = web.StreamResponse(status=resp.status, headers=resp_headers)
            await proxy_resp.prepare(request)
            try:
                async for chunk in resp.content.iter_any():
                    await proxy_resp.write(chunk)
                await proxy_resp.write_eof()
            except (ConnectionResetError, BrokenPipeError, ConnectionError):
                # Client (e.g. ffmpeg probing) hung up mid-stream - not an error.
                log.info("Client disconnected mid-stream for %s", target_url)
            return proxy_resp
    except (ConnectionResetError, BrokenPipeError, ConnectionError):
        log.info("Client disconnected before response for %s", target_url)
        return web.Response(status=499, text="client closed connection")
    except Exception:
        log.exception("HTTP proxy error for %s", target_url)
        return web.Response(status=502, text="proxy error")


async def on_startup(app: web.Application):
    # aiohttp's default ClientTimeout(total=300) kills any request - including
    # long-lived stream responses - after 300s regardless of ongoing activity.
    # Streams must stay open indefinitely; keep a sock_read idle timeout so a
    # genuinely stuck connection still gets reaped. See "Update" below.
    timeout = aiohttp.ClientTimeout(total=None, sock_connect=10, sock_read=60)
    app["session"] = aiohttp.ClientSession(timeout=timeout)


async def on_cleanup(app: web.Application):
    await app["session"].close()


def make_http_app() -> web.Application:
    app = web.Application()
    app.router.add_route("*", "/{path:.*}", handle_http)
    app.on_startup.append(on_startup)
    app.on_cleanup.append(on_cleanup)
    return app


async def _relay(src: asyncio.StreamReader, dst: asyncio.StreamWriter):
    try:
        while True:
            data = await src.read(65536)
            if not data:
                break
            dst.write(data)
            await dst.drain()
    except (ConnectionResetError, BrokenPipeError):
        pass
    finally:
        dst.close()


async def handle_htsp(reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
    try:
        remote_reader, remote_writer = await asyncio.open_connection(TVH_HOST, TVH_HTSP_PORT)
    except OSError:
        log.exception("HTSP passthrough: cannot reach upstream")
        writer.close()
        return
    await asyncio.gather(
        _relay(reader, remote_writer),
        _relay(remote_reader, writer),
    )


async def main():
    http_app = make_http_app()
    runner = web.AppRunner(http_app)
    await runner.setup()
    site = web.TCPSite(runner, "0.0.0.0", PROXY_HTTP_PORT)
    await site.start()
    log.info("HTTP proxy listening on :%d -> %s:%d", PROXY_HTTP_PORT, TVH_HOST, TVH_HTTP_PORT)

    htsp_server = await asyncio.start_server(handle_htsp, "0.0.0.0", PROXY_HTSP_PORT)
    log.info("HTSP passthrough listening on :%d -> %s:%d", PROXY_HTSP_PORT, TVH_HOST, TVH_HTSP_PORT)

    async with htsp_server:
        await htsp_server.serve_forever()


if __name__ == "__main__":
    asyncio.run(main())
```

Systemd unit:

```ini
[Unit]
Description=TVHeadend Auth-Fixing Reverse Proxy (for Jellyfin plugin imagecache bug)
After=tvheadend.service
Requires=tvheadend.service

[Service]
Type=simple
ExecStart=/usr/bin/python3 /opt/tvh_auth_proxy.py
Restart=always
RestartSec=3
User=root

[Install]
WantedBy=multi-user.target
```

(`Requires=tvheadend.service` stops the proxy whenever TVH restarts, e.g. for a package update, but doesn't restart it once TVH is back — `Restart=on-failure` won't catch that since the stop isn't a failure. Use `Restart=always`.)

Tvheadend-side requirements:
1. Dedicated access entry (Configuration → Users → Access Entries) with the permissions this plugin's docs recommend (Streaming: Basic/Advanced/HTSP, Video Recorder: Basic/HTSP/View all, Web Interface enabled). If the proxy runs on the same host and talks to TVH over loopback, the entry's allowed network/prefix needs to include `127.0.0.1/32` too — otherwise TVH's IP-prefix check rejects the proxy's request with 403 even though auth itself succeeded.
2. Auth mode set to "Plain + Digest" (Configuration → General → Base → HTTP Server Settings) so the proxy can use Basic auth instead of implementing a Digest handshake.

In the Jellyfin plugin settings, point HTTP port / HTSP port at the proxy's ports instead of Tvheadend's real ones; hostname/username/password stay the same.

## Update: streams through the proxy died after ~300s

Found later, separate from the icon issue: Live TV through the proxy reliably cut off after ~299–300s (`PES packet size mismatch`/`corrupt input packet` errors right at the cutoff — a consequence of the TCP connection dying mid-packet, not the cause). Same channel direct against Tvheadend, proxy bypassed: stable for 10+ minutes. Reproduced across two different tuners on the same mux, ruling out tuner/reception.

Cause: `on_startup()` created `aiohttp.ClientSession()` with no explicit timeout. aiohttp's default is `ClientTimeout(total=300)` — a **total**, not idle, timeout that kills any request after 300s regardless of ongoing activity. Never noticed on the short `/imagecache/*` requests; fatal for a stream meant to stay open for hours.

Fix (already applied above): `ClientTimeout(total=None, sock_connect=10, sock_read=60)` — no total limit, but a connection still gets reaped after 60s with zero new data. Verified: same channel through the proxy ran 380s straight with no cutoff (test ended by its own timeout, not the proxy).

## Stale DB state after fixing auth

If icons still don't load after the auth fix, it's a separate issue: Jellyfin keeps Live TV channel/program items, including per-image failure state, in `jellyfin.db`, independent of whether the plugin is installed. Confirmed by uninstalling the plugin completely (no config, no DLL) — the old channel/program rows stayed in the DB, and reinstalling the plugin matched/reused them instead of creating new ones. Guide refreshes and Jellyfin restarts don't clear this.

To force fresh fetch attempts, stop Jellyfin, back up the DB, and purge the Live TV rows:

```bash
# 1. Backup first
cp -a /var/lib/jellyfin/data/jellyfin.db /var/lib/jellyfin/data/jellyfin.db.bak-$(date +%F)

# 2. Stop Jellyfin
systemctl stop jellyfin   # or your container/docker equivalent

# 3. Purge Live TV items and their dependent rows
sqlite3 /var/lib/jellyfin/data/jellyfin.db <<'SQL'
BEGIN;
DELETE FROM BaseItemImageInfos
  WHERE ItemId IN (SELECT Id FROM BaseItems WHERE Type LIKE '%.LiveTv.%');
DELETE FROM BaseItemProviders
  WHERE ItemId IN (SELECT Id FROM BaseItems WHERE Type LIKE '%.LiveTv.%');
DELETE FROM BaseItems WHERE Type LIKE '%.LiveTv.%';
COMMIT;
VACUUM;
SQL

# 4. Clear the filesystem-side Live TV cache too
rm -rf /var/lib/jellyfin/metadata/channels/*
rm -rf /var/lib/jellyfin/metadata/views/livetv/*

# 5. Start Jellyfin again, then (re)install/configure the TVHeadend plugin
#    and trigger a guide data refresh from scratch.
systemctl start jellyfin
```

`BaseItemImageInfos` is the row that matters — a cleanup script found online (https://gist.github.com/Pyrynot/10baf08b63e88508c546d9ba96544da6) only deletes from `BaseItems`/`BaseItemProviders`, and images still wouldn't reload with that alone; the stale per-image record in `BaseItemImageInfos` was what blocked the retry.
